# Development environment configuration
# Overrides base.yaml settings
name: Azure OpenAI Proxy
version: 1.0.9
port: 3010
routing:
  strategy: round_robin
  retries: 3
  timeout: 60
logging:
  file: ../logs/app.log
  max_size: 5242880
  backup_count: 3
  feishu_webhook: ${FEISHU_WEBHOOK_URL}
monitoring:
  stats_window_minutes: 5
  additional_windows:
  - 15
  - 30
  - 60
