# Development environment configuration
# Overrides base.yaml settings

# More verbose logging
logging:
  level: "DEBUG"

# Example instance configuration for development
instances:
  # - name: "dev-instance-1"
  #   provider_type: "azure"
  #   api_key: "${AZURE_API_KEY_DEV}"
  #   api_base: "https://dev-instance.openai.azure.com"
  #   api_version: "2024-08-01-preview"
  #   priority: 1
  #   weight: 100
  #   max_tpm: 240000
  #   supported_models:
  #     - "gpt-4o-mini"
  #     - "gpt-4o"
  #   model_deployments:
  #     gpt-4o-mini: "gpt4omini"
  #     gpt-4o: "gpt4o" 